[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = false
enable_mypy = false
mypy_preset = "strict"
line_length = 88
py_version = "py310"

[[tool.pysen.lint.mypy_targets]]
paths = ["."]

[tool.pysen.lint.source]
includes = ["."]
excludes = ["venv/"]
exclude_globs = ["**/migrations/"]
