[tool.flake8]
per-file-ignores = ["__init__.py:F401"]
max-line-length = 88
extend-exclude = ["venv", "migrations", "manage.py", "settings.py"]

[tool.black]
line-length = 88
extend-exclude = """
(
    migrations/
    | manage.py
)
"""

[tool.isort]
profile = "black"
skip_gitignore = true
extend_skip_glob = ["**/migrations/*", "manage.py"]
