[tool.flake8]
per-file-ignores = ["__init__.py:F401"]
max-line-length = 88
extend-exclude = ["venv", "migrations", "manage.py", "settings.py"]

[tool.black]
line-length = 88
extend-exclude = """
(
    migrations/
    | manage.py
)
"""

[tool.isort]
profile = "black"
skip_gitignore = true
extend_skip_glob = ["**/migrations/*", "manage.py"]

[tool.mypy]
python_version = "3.9"
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
exclude = ['^manage\.py$', '^settings\.py$', '^migrations$', 'venv']
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "book_management.settings"
