# Generated by Django 4.2 on 2023-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="書籍分類コード",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="書籍分類名")),
            ],
            options={
                "verbose_name": "書籍分類",
                "verbose_name_plural": "書籍分類",
                "db_table": "classifications",
                "ordering": ("code",),
            },
        ),
    ]
