# Generated by Django 4.2 on 2023-04-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationDetail",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="書籍分類詳細コード",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="書籍分類詳細名")),
                (
                    "classification",
                    models.ForeignKey(
                        db_column="classification_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classification_details",
                        to="books.classification",
                        verbose_name="書籍分類詳細",
                    ),
                ),
            ],
            options={
                "verbose_name": "書籍分類詳細",
                "verbose_name_plural": "書籍分類詳細",
                "db_table": "classification_details",
                "ordering": ("code",),
            },
        ),
    ]
