# Generated by Django 4.2 on 2023-04-28 00:54

import core.models
from django.db import migrations, models
import django.db.models.deletion
import ulid


class Migration(migrations.Migration):
    dependencies = [
        ("divisions", "0002_alter_division_options_alter_division_code_and_more"),
        ("books", "0002_classificationdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "id",
                    core.models.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                        verbose_name="書籍ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="タイトル")),
                (
                    "authors",
                    models.TextField(blank=True, null=True, verbose_name="著者または訳者"),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="出版社"
                    ),
                ),
                (
                    "published_at",
                    models.DateField(blank=True, null=True, verbose_name="発行日"),
                ),
                ("disposed", models.BooleanField(default=False, verbose_name="廃棄済み")),
                (
                    "disposed_at",
                    models.DateField(blank=True, null=True, verbose_name="廃棄日"),
                ),
                (
                    "classification_detail",
                    models.ForeignKey(
                        db_column="classification_detail_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classification_detail_books",
                        to="books.classificationdetail",
                        verbose_name="書籍分類詳細",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        db_column="division_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="divisions.division",
                        verbose_name="管理部署",
                    ),
                ),
            ],
            options={
                "verbose_name": "書籍",
                "verbose_name_plural": "書籍",
                "db_table": "books",
                "ordering": ("id",),
            },
        ),
    ]
